export enum AvailableIcons {
    FontAwesome = "fa",
    AntDesign = "ai",
    Bootstrap = "bi",
    Feather = "fi",
    GameIcons = "gi",
    Heroicons = "hi",
    Heroicons2 = "hi2",
    IcoMoon = "im",
    Ionicons4 = "io",
    Ionicons5 = "io5",
    MaterialDesign = "md",
    RemixIcon = "ri",
    SimpleIcons = "si",
    SimpleLineIcons = "sl",
    TablerIcons = "tb",
    ThemifyIcons = "ti",
    VSCodeIcons = "vsc",
    WeatherIcons = "wi",
    BootstrapIcons = "bs",
    CssGG = "cg",
    Devicons = "di",
    FlatColorIcons = "fc",
    GrommetIcons = "gr",
    LucideIcons = "lu",
    RadixIcons = "rx",
}